### PR TITLE
Swagger-UI

### LINKED ISSUE #57: FEATURE: API Documentation using Swagger
**What?**
Add API Documentation using Swagger

**Why?**
We need to have better documentation of our API for other devs to learn about the project and to make our frontend development easier.

**How?**
NOTE: THESE INSTRUCTIONS MIGHT NOT WORK IN SPRINGBOOT 3.0 (you'll need to utilize your Google skills)
Swagger is a library that automatically generates documentation for us

First, add Swagger to the dependency list in pom.xml
- Search up (springfox-boot-starter 3.0.0)

Next, go to your @ SpringBootApplication annotation (main file) and add @EnableSwagger2

Finally, create a “config” package in src/main/java, and, within it, create a Configuration file containing a Bean called SwaggerConfig:
              @ Configuration
              public class SwaggerConfig implements WebMvcConfigurer {
              @ Bean
              Public Docket appApi() {
                             Docket docket = new Docket(DocumentationType.SWAGGER_2).select().apis(RequestHandlerSelectors.basePackage(“[enter path to controller package]”).paths.((PathSelectors.regex(“/.”))).build();
                             return docket;
              }

You’ll find the docs as a JSON file in …/v2/”api-docs” endpoint
You’ll find the docs with nice UI in …/”swagger-ui” endpoint

We can add a few more annotations to make the swagger documentation more informative
- @ApiOperation (look up specifics)
- @ApiParam (look up specifics)

We can also specify the format of data our endpoints will consume and produce
- Ex. @PostMapping(path = “/login”, consumes = {“application/json”}, produces = {“application/json”}}
- The default is json

### PR DESCRIPTION
**Pull request by imvignesh003**
Ticket
Closes #57

Information
What?
I have added Swagger Documentation to the module

Why?
To make a simple UI for working with endpoints

Code Checklist
[x] Did I manually test my changes, or contact @Adam1302 to test my changes on the remote branch?
[x] Did I document my changes such that a new dev or a learner might understand them?

### CODE REVIEW

**Review by Adam1302 — APPROVED** [review]

**Comment by Adam1302** [comment]
Good to merge @imvignesh003

**Comment by imvignesh003** [comment]
Happy for my 1st Open Source Contribution @Adam1302. Is everything over? the PR remains unmergerd?

**Comment by Adam1302** [comment]
@imvignesh003 are you able to select "squash and merge"? Or does that option not display for you?

**Comment by imvignesh003** [comment]
image
I can find the above in the settings page of my repo...

**Comment by Adam1302** [comment]
But you can't see this on the PR, correct?
Screen Shot 2024-05-23 at 10 07 49 PM

**Comment by imvignesh003** [comment]
I don't see any selection in my PR @Adam1302. Kindly do merge it.

**Comment by Adam1302** [comment]
Merged

**Pull request merged**
